### ISSUE TITLE
IE11 Year Picker issue

### ISSUE THREAD

**Issue by the1979** [chrisdavies/tiny-date-picker#53] opened 2017-11-15 20:33 UTC
Firstly, thanks for the great component guys!

I'm busy with cross browser testing on a project and running into issues with the "year picker" behaviour on IE11 / Windows 10.

### To reproduce:
1. Open http://christophilus.com/tiny-date-picker/ in IE11
2. Launch the "Example Modal"
3. Click the year to open the "year picker"
4. Scroll the list so that the currently selected year (let's say 2017) is **out of view**
5. Select a year in the list in front of you
6. The list "jumps" up so that the previously selected year (2017) is in view again. The new year that was clicked has not been selected and the year picker has not been closed.

One would obviously expect the newly clicked year to be selected, year picker closed, calendar view shown and the year updated to your new selection.

I've tracked down where in the code things are going wrong but not yet been able to fix:

When the new year is clicked, one would expect that `onChooseYear()` would be executed (https://github.com/chrisdavies/tiny-date-picker/blob/master/dist/tiny-date-picker.js#L570-L575), but this is never called.

The problem (I believe) is in `focusCurrent()` (https://github.com/chrisdavies/tiny-date-picker/blob/master/dist/tiny-date-picker.js#L852-L855) that is called from the `mousedown` event handler.

Inside `focusCurrent` we're placing focus on the originally selected year (2017 in example above) and that seems to be somehow hijacking the `click` event on the new year's element in IE11 because the list is scrolled so that 2017 is visible in the view again.

You'll notice that, if you don't scroll the originally selected year out of view completely when you're selecting a new year, the selection works fine. I expect this is because IE doesn't have to scroll the original element into view again when it calls `focus()`.

I'll submit a pull request if I find a solution, but please let me know if you have any ideas for solving this.

**Comment by chrisdavies** [comment] 2017-11-16 01:59
Interesting. Thanks for reporting this. I'll take a look at it tomorrow. IE support has been tricky. It's most likely due to a hacky timing issue. At one point, I had to sprinkle `setTimeout` invocations in various event handlers to make IE happy. May have to resort to that again as a stop gap measure.

**Comment by the1979** [comment] 2017-11-16 08:13
Good old IE...

I briefly tried to compare the event execution order between Chrome and IE, and everything looked similar up until the point that the original element is focused. It's like in IE the clicked element is scrolled away from under the mouse pointer by the time the `mouseup` phase of `click` is fired, which means the `click` event is never recorded.

Thanks for looking at this.

**Comment by chrisdavies** [comment] 2017-11-16 17:22
Hm. I wasn't able to reproduce this issue, unfortunately. I'm running IE in an underpowered VM on my Mac, though. If you run Edge and then emulate IE 11, does the bug still reproduce?

**Comment by the1979** [comment] 2017-11-16 21:03
No issues when emulating IE 11 on latest Edge, no. That emulator looks like a useless piece of crap though.

**Comment by leeoniya** [comment] 2017-11-16 21:16
IE emulation is Edge is trash. even actual IE11 on windows 10 does not work the same as IE11 on Windows 7 & 8. The only real test is using a Win7 IE11 vm from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by chrisdavies** [comment] 2017-11-16 21:17
Ah. I need to download an older VM image, then. I was testing in Edge emulation mode.

**Comment by chrisdavies** [comment] 2017-11-17 16:32
OK. It should be fixed in the latest release.

The problem was in some logic that prevents the date picker from hiding when you click empty-space within it. That logic was expecting a focus behavior that Chrome + FF + Safari exhibit, but IE (of course) does its own thing.

*sigh*

I learned something, though, which is that Edge's IE emulation is not reliable. Thanks @leeoniya and @the1979 for the help!

**Closed by chrisdavies** 2017-11-17 16:32 UTC
