### ISSUE TITLE
Selecting Date in IE 11 on Win 7 causes date picker to reappear

### ISSUE THREAD

**Issue by nerdgore** [chrisdavies/tiny-date-picker#16] opened 2016-09-13 11:47 UTC
This one is a bit tricky.
A colleague can reliably reproduce this on mentioned setup. I have IE 11 on Win 8 in Virtual Box and can not. Looking at the code I can not immediately see any issue there. I could imagine though it has something to do with the input field regaining focus after the date picker closes.

_Actual Behavior_
- click in input to pen date picker
- select date
- date picker disappears and immediately reappears  
  closing via button works, but selecting a date will trigger the same behaviour over and over again

_Expected Behaviour_
- click in input to pen date picker
- select date
- date picker closes

**Comment by chrisdavies** [comment] 2016-09-13 14:22
Yeah. I can't repro either using the IE11 remote access tool:

https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/

It sounds like a bug that cropped up early with the date picker, where when you closed it, it set focus to the input field and that focus event triggered the date picker to show again.

If you look at the hide function:

```
function hide() {
    if (!body.contains(el)) return;
    isHiding = 1;
    input.focus(); // This is the probable culprit
    input.selectionEnd = input.selectionStart;
    body.removeChild(el); // Removes the calendar
    body.removeChild(focusCatcher); // Removes a hacky element that catches focus when tabbing-off calendar
    el.className = el.className.replace(' dp-visible', '');
    setTimeout(function () { isHiding = 0 }, 1); // << This is the probable culprit: prevents re-focus from showing the calendar for a time
  }
```

Can you try bumping up that setTimeout value for your colleague and seeing how it affects things? 10 ms should still be reasonable.

**Comment by chrisdavies** [comment] 2016-09-14 21:35
@nerdgore Should be fixed. Wasn't able to repro, but I think I found the issue. It's a browser speed issue. That's the problem with the hacky use of setTimeout.

**Comment by nerdgore** [comment] 2016-09-16 07:03
Sounds reasonable. I ran into timeout issues myself quite a few times. From the top of my head I would think that deliberately refocusing the text field but discarding that event might be the best solution in this case.

We bumped up the timeout to 50ms but had no success on that specific system. All other VMs (even with the same setup) worked fine.

Thank you for your thorough support.

**Comment by chrisdavies** [comment] 2016-09-18 23:15
I had a bit of trouble just discarding the next event, as it seemed to fire inconsistently across browsers, hence the timeout. Really odd about your coworker's machine. I'll leave this open and hopefully, we can track it down.

**Comment by chrisdavies** [comment] 2016-12-10 17:14
Hi. I know this is an old issue.

I've got a preview of v2 up here: http://chrisdavies.github.io/tiny-date-picker/

I wonder if the problem is still around for this version. Since I was never able to repro it in the first place, could you confirm that it is fixed/still an issue here?

Thanks!

**Closed** 2016-12-13 03:30 UTC

**Comment by Vringe** [comment] 2018-12-21 15:48
Same issue here on IE11:
- Clicking into input field -> Datepicker appears
- Selecting a date -> Datepicker is closing and reappears directly
- Now all days are disabled (future and past)

![tinydatepicker_bug](https://user-images.githubusercontent.com/11569136/50350700-319e1400-0540-11e9-91a0-7665636c18f4.gif)
